# config.yaml

schedule:
  hour: 12
  minute: 00

request:
  url: "http://classes.tju.edu.cn/eams/stdElectCourse!batchOperator.action?profileId=xxxx"
  headers:
    Accept: "text/html, */*; q=0.01"
    Accept-Encoding: "gzip, deflate"
    Accept-Language: "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"
    Connection: "keep-alive"
    Content-Type: "application/x-www-form-urlencoded; charset=UTF-8"
    Host: "classes.tju.edu.cn"
    Origin: "http://classes.tju.edu.cn"
    Referer: "http://classes.tju.edu.cn/eams/stdElectCourse!defaultPage.action"
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0"
    X-Requested-With: "XMLHttpRequest"
    cookie: ""

courses:
  - "465379" #科技论文写作 石广清 1 5-6
  - "465453" #随机过程基础 勇 1 3-4 3 5-6
  - "465436" #应用统计学 杨雪 2 1-2 4 3-4
  - "465380" #科技论文写作 石广清 1 7-8
  - "465433" #应用统计学 胡玉梅 1 1-2 3 3-4
  - "465434" #应用统计学 胡玉梅 3 1-2 5 3-4